### PR TITLE
Documentation Overhaul

### PR DESCRIPTION
**Pull request by andrewauclair**

### CODE REVIEW

**Comment by tlf30** [comment]
Just as an idea for you, I have been using Writerside by Jetbrains for my documentation and really like it. I have my documentation directly in the project and get the advantage of generating HTML outputs for my documentation. The documentation is written using markdown, but also with additional xml like features added by jetbrains. There is a plugin for IDEA for it, but also as a standalone IDE. Something worth looking into.

**Comment by andrewauclair** [comment]
@tlf30 Thanks for the reminder. I've seen it before but haven't tried it for more than a few minutes. Do you use the plugin or the standalone version?

**Comment by tlf30** [comment]
I am using both, I like the plugin the best since I can use the doc preview pane while working on the project.

**Comment by andrewauclair** [comment]
@tlf30 Writerside is great. Started with markdown but now I'm trying to restructure some of it with the semantic markup because that is pretty powerful. I'm hoping I can throw the html output on my github.io and link to that to display the actual web version.

**Comment by andrewauclair** [comment]
https://andrewauclair.github.io/modern-docking

works just as I had hoped. I might link directly to the starting topic because the index redirect is a little annoying.

**Pull request merged**
